project_id = "otpcqazflitoexnhcwza"

[functions.discord-webhook]
verify_jwt = false

[functions.discord-bot]
verify_jwt = false

[functions.order-webhook-notifier]
verify_jwt = false

[functions.sync-discord-roles]
verify_jwt = true

[functions.update-profile-ip]
verify_jwt = true

[functions.admin-orders]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.discord-activity]
verify_jwt = false