// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzbpjvtrfnjzyzfhlmad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6YnBqdnRyZm5qenl6ZmhsbWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTgzNTcsImV4cCI6MjA2NzU5NDM1N30.ojFp-RfUXne8uRJljj9fWKD72W0oge_GzHvT-Wmask4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});