// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqpjgfvsxxlwgcapxres.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxcGpnZnZzeHhsd2djYXB4cmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzU3NjgsImV4cCI6MjA2OTc1MTc2OH0.8BUxErKtgHVbaMY-_tjfrOV42xQTtYuECvrAzkfCu5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});