// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otpcqazflitoexnhcwza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cGNxYXpmbGl0b2V4bmhjd3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1OTIxNDAsImV4cCI6MjA3OTE2ODE0MH0.hPneoAuhhwqXt1hrdUggP4hjhraCHLczXA9oCb28CHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});